#!/usr/bin/env ruby

require 'highline/import'
require 'colorize'
require_relative 'lib/environment'
require_relative 'lib/ascii'

color_dark = :black
color_light = :light_yellow

environment = ARGV[0]
# puts environment
Environment.environment = environment || "production"



# puts String.colors
# String.colors - return array of all possible colors names
# puts String.modes # - return array of all possible modes
# String.color_matrix #- displays color matrix with color names
# puts String.color_matrix("FOO") #- display color matrix with "FOO" text

Ascii.welcome

loop do
  Ascii.menu
  choose do |menu|
    menu.prompt = "What would you like to do?".bold.colorize(:color => color_dark, :background => color_light)
    menu.choice("Add") do |chosen|
      Location.add
    end
    menu.choice("View") do |chosen|
      search_city = Location.fetch_query('view')
      Location.find(search_city).each do |record|
        print record.to_s.colorize(:color => color_light, :background => color_dark)
        puts ""
      end
      puts ""
    end
    menu.choice("Edit") do |chosen|
      old_update_city = Location.fetch_query('update')
      new_update_city = Location.fetch_replacement(old_update_city)
      puts "Old Location: #{old_update_city.inspect}".colorize(:color => color_light, :background => color_dark)
      puts "Updated Location: #{new_update_city.inspect}".colorize(:color => color_dark, :background => color_light)
      Location.update(old_update_city, new_update_city)
    end
    menu.choice("Remove") do |chosen|
      delete_city = Location.fetch_query('remove')
      Location.remove(delete_city)
    end
    menu.choice("EXIT") do |chosen|
      Ascii.goodbye
      exit
    end
  end
end





